API_KEY = "PK7IJNU5PF46X2MJCFAB"
SECRET_KEY = "WbIZu5kHkPUReBnwV3TOZZ7qAVs3vXHaP0qB8ZdC"

ALPACA_CONFIG = {
    "API_KEY": "PK7IJNU5PF46X2MJCFAB",
    "API_SECRET": "WbIZu5kHkPUReBnwV3TOZZ7qAVs3vXHaP0qB8ZdC",
    "ENDPOINT": "https://paper-api.alpaca.markets",
}